#pragma once
#if defined(_MSC_VER) && !defined(__clang__)
// Workaround for MSVC: expension rules are different so we need some extra macro.
#    define STRONG19_MSVC_EXPAND(...) __VA_ARGS__
#    define STRONG19_MSVC_DELAY(X, ...) STRONG19_MSVC_EXPAND(X(__VA_ARGS__))
#    define STRONG19_MSVC_EMPTY / ##**## /
#else
#    define STRONG19_MSVC_EXPAND(...) __VA_ARGS__
#    define STRONG19_MSVC_DELAY(X, ...) X(__VA_ARGS__)
#    define STRONG19_MSVC_EMPTY
#endif

#define STRONG19_DELAY(X, ...) STRONG19_MSVC_EXPAND(X(__VA_ARGS__))
#define STRONG19_DELAY2(X, ...) STRONG19_MSVC_EXPAND(X(__VA_ARGS__))
#define STRONG19_TAIL(A, ...) __VA_ARGS__

#define STRONG19_REMOVEPAREN(A) STRONG19_DELAY(STRONG19_REMOVEPAREN2, STRONG19_REMOVEPAREN_HELPER A)
#define STRONG19_REMOVEPAREN2(...) STRONG19_DELAY2(STRONG19_TAIL, STRONG19_REMOVEPAREN_HELPER_##__VA_ARGS__)
#define STRONG19_REMOVEPAREN_HELPER(...) _, __VA_ARGS__
#define STRONG19_REMOVEPAREN_HELPER_STRONG19_REMOVEPAREN_HELPER ,

#define STRONG19_COMMA_TAIL(A, ...) , ##__VA_ARGS__

#define STRONG19_COMMA_REMOVEPAREN(A) STRONG19_DELAY(STRONG19_COMMA_REMOVEPAREN2, STRONG19_COMMA_REMOVEPAREN_HELPER A)
#define STRONG19_COMMA_REMOVEPAREN2(...)                                                                               \
    STRONG19_DELAY2(STRONG19_COMMA_TAIL, STRONG19_COMMA_REMOVEPAREN_HELPER_##__VA_ARGS__)
#define STRONG19_COMMA_REMOVEPAREN_HELPER(...) _, __VA_ARGS__
#define STRONG19_COMMA_REMOVEPAREN_HELPER_STRONG19_COMMA_REMOVEPAREN_HELPER ,
