name: CMake-Tests

on: push

jobs:
  windows:
    name: "Windows"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            preset: "msvc"

          - os: windows-2022
            preset: "msvc"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Tools Ninja and mvsc
        uses: ilammy/msvc-dev-cmd@v1

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build and Test Debug
        run: script/test_cmake.bat ${{ matrix.preset }} debug

      - name: Build and Test Release
        run: script/test_cmake.bat ${{ matrix.preset }} release

  linux:
    name: "Linux"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "arbmind/cmake-clang:3.25.1-13"
            preset: "clang"
          - image: "arbmind/cmake-clang:3.25.1-14"
            preset: "clang"
          - image: "arbmind/cmake-clang-libstdcpp:3.25.1-15-12"
            preset: "clang-libstdcpp"
          - image: "arbmind/cmake-gcc:3.25.1-11"
            preset: "gcc"
          - image: "arbmind/cmake-gcc:3.25.1-12"
            preset: "gcc"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test Debug
        run: >-
          docker run --rm -v ${GITHUB_WORKSPACE}:/project -w /project
          ${{ matrix.image }}
          script/test_cmake.sh ${{ matrix.preset }} debug

      - name: Build and Test Release
        run: >-
          docker run --rm -v ${GITHUB_WORKSPACE}:/project -w /project
          ${{ matrix.image }}
          script/test_cmake.sh ${{ matrix.preset }} release
