name: CMake-Tests

on: push

jobs:
  windows:
    name: "Windows"
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: "msvc2019"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tools Ninja and mvsc
        uses: ilammy/msvc-dev-cmd@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build and Test Debug
        run: script/test_cmake.bat ${{ matrix.preset }} debug

      - name: Build and Test Release
        run: script/test_cmake.bat ${{ matrix.preset }} release

  linux:
    name: "Linux"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "arbmind/cmake-clang:3.22.3-13"
            preset: "clang"
          - image: "arbmind/cmake-clang:3.22.3-14"
            preset: "clang"
          - image: "arbmind/cmake-clang-libstdcpp:3.22.3-14-11"
            preset: "clang-libstdcpp"
          - image: "arbmind/cmake-gcc:3.22.3-11"
            preset: "gcc"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test Debug
        run: >-
          docker run --rm -v ${GITHUB_WORKSPACE}:/project -w /project
          ${{ matrix.image }}
          script/test_cmake.sh ${{ matrix.preset }} debug

      - name: Build and Test Release
        run: >-
          docker run --rm -v ${GITHUB_WORKSPACE}:/project -w /project
          ${{ matrix.image }}
          script/test_cmake.sh ${{ matrix.preset }} release
